apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ include "twentycrm.workername" . }}
  name: {{ include "twentycrm.workername" . }}
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  selector:
    matchLabels:
      app: {{ include "twentycrm.workername" . }}
  template:
    metadata:
      labels:
        app: {{ include "twentycrm.workername" . }}
    spec:
      containers:
        - name: twentycrm
          image: {{ .Values.worker.image }}
          imagePullPolicy: Always
          {{- with .Values.worker.env }}
          env:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          command:
            - yarn
            - worker:prod
          {{- with .Values.worker.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          stdin: true
          tty: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
