apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{- printf "%s-pvc" ( include "twentycrm.servername" .) }}
spec:
  storageClassName: {{- default .Values.persistence.default.storageClass .Values.persistence.server.storageClass }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{- default .Values.persistence.default.size .Values.persistence.server.size }}
