{{- if .Values.redis.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "twentycrm.redisname" . }}
spec:
  internalTrafficPolicy: Cluster
  ports:
    - port: 6379
      protocol: TCP
      targetPort: 6379
  selector:
    app: {{ include "twentycrm.redisname" . }}
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
  type: ClusterIP
{{- end }}