{{- if .Values.redis.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "twentycrm.redisname" . }}
  labels:
    {{- include "twentycrm.labels" . | nindent 4 }}
    app.twentycrm/component: {{ include "twentycrm.redisname" . }}
spec:
  internalTrafficPolicy: Cluster
  ports:
    - port: 6379
      protocol: TCP
      targetPort: 6379
  selector:
    {{- include "twentycrm.selectorLabels" . | nindent 4 }}
    app.twentycrm/component: {{ include "twentycrm.redisname" . }}
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
  type: ClusterIP
{{- end }}
