{{- if .Values.role }}
kind: {{ .Values.role.type }}Binding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "frigate.serviceAccountName" . }}
  labels:
    {{- include "frigate.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: {{ .Values.role.type }}
  name: {{ include "frigate.serviceAccountName" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "frigate.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}