## THE BELOW COMMENTED OUT SECTION IS NOT YET IMPLEMENTED BUT A MUST
## TO HAVE SET OF FEATURES IN CASE THE CHART IS USED FURTHER ON
# # This is to setup the liveness and readiness probes more information can be found here: https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/
# livenessProbe:
#   httpGet:
#     path: /
#     port: http
# readinessProbe:
#   httpGet:
#     path: /
#     port: http

# # This section is for setting up autoscaling more information can be found here: https://kubernetes.io/docs/concepts/workloads/autoscaling/
autoscaling:
  enabled: false
#   minReplicas: 1
#   maxReplicas: 100
#   targetCPUUtilizationPercentage: 80
#   # targetMemoryUtilizationPercentage: 80

# nodeSelector: {}

# tolerations: []

# affinity: {}
## END OF PLANNED IMPLEMENTATIONS SECTION

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

postgresql:
  enabled: true
  image: postgres:16
  env:
    - name: POSTGRES_USER
      value: nocobase
    - name: POSTGRES_DB
      value: nocobase
    - name: POSTGRES_PASSWORD
      value: nocobase
  resources:
    requests:
      memory: "256Mi"
      cpu: "250m"
    limits:
      memory: "1024Mi"
      cpu: "1000m"
  persistence:
    storageClass: local-path
    size: 10Gi

redis:
  enabled: true
  image: redis/redis-stack-server:latest
  env:
    - name: PORT
      value: "6379"
  resources:
    requests:
      memory: "256Mi"
      cpu: "150m"
    limits:
      memory: "512Mi"
      cpu: "300m"

server:
  image: nocobase/nocobase:latest
  env:
    # - name: TZ
    #   value: Asia/Yerevan # UTC
    - name: APP_ENV
      value: development # production
    # - name: APP_KEY
    #   value: app-secret-key
    # - name: APP_PORT
    #   value: "13000"
    # - name: API_BASE_PATH
    #   value: "/api/"
    # # - name: CLUSTER_MODE
    # #   value: max # -1, n
    # # - name: PLUGIN_PACKAGE_PREFIX
    # #   value: "@nocobase/plugin-,@nocobase/preset-"
    # - name: DB_DIALECT
    #   value: postgres # mysql, sqlite
    # # - name: DB_STORAGE
    # #   value: /sqlite/db/path.db
    # - name: DB_HOST
    #   value: "nocobase-db.nocobase"
    # - name: DB_PORT
    #   value: "5432"
    # - name: DB_DATABASE
    #   value: default
    # - name: DB_USER
    #   value: postgres
    # - name: DB_PASSWORD
    #   value: postgres
    # - name: DB_TABLE_PREFIX
    #   value: "nocobase_"
    # - name: DB_LOGGING
    #   value: "off"
    # - name: NOCOBASE_PKG_USERNAME
    #   value: ""
    # - name: NOCOBASE_PKG_PASSWORD
    #   value: ""
    # - name: LOGGER_TRANSPORT
    #   value: console # file,dailyRotateFile
    # # - name: LOGGER_BASE_PATH
    # #   value: /path/to/file.log
    # - name: LOGGER_LEVEL
    #   value: info # error, warn, debug, trace
    # # - name: LOGGER_MAX_FILES
    # #   value: 14d
    # # - name: LOGGER_MAX_SIZE
    # #   value: "20971520" # [n]k/m/g for dailyRotateFile
    # - name: LOGGER_FORMAT
    #   value: json # console, logfmt, delimiter
    # - name: CACHE_DEFAULT_STORE
    #   value: redis
    # - name: CACHE_MEMORY_MAX
    #   value: "2000"
    # - name: CACHE_REDIS_URL
    #   value: "redis://nocobase-redis.nocobase:6379"
    # # - name: TELEMETRY_ENABLED
    # #   value: "on"
    # # - name: TELEMETRY_METRIC_READER
    # #   value: "console,prometheus"
    # # - name: TELEMETRY_TRACE_PROCESSOR
    # #   value: "console"
  resources:
    requests:
      memory: "256Mi"
      cpu: "250m"
    limits:
      memory: "1024Mi"
      cpu: "1000m"
  persistence:
    storageClass: local-path
    size: 10Gi

ingress:
  enabled: false
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
    # nginx.ingress.kubernetes.io/configuration-snippet: |
    #   more_set_headers "X-Forwarded-For $http_x_forwarded_for";
    # nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
    # nginx.ingress.kubernetes.io/backend-protocol: HTTP
  hosts:
    - host: crm.example.local
      paths:
        - path: /
          pathType: Prefix
  tls: []
  #  - secretName: crm-example-tls
  #    hosts:
  #      - crm.example.local