apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ printf "%s-pvc" ( include "nocobase.servername" .) }}
  labels:
    {{- include "nocobase.labels" . | nindent 4 }}
spec:
  storageClassName: {{ .Values.server.persistence.storageClass }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.server.persistence.size }}
