{{- if .Values.postgresql.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "nocobase.dbname" . }}
  labels:
    {{- include "nocobase.labels" . | nindent 4 }}
    app.nocobase/component: {{ include "nocobase.dbname" . }}
spec:
  internalTrafficPolicy: Cluster
  ports:
    - port: 5432
      protocol: TCP
      targetPort: 5432
  selector:
    {{- include "nocobase.selectorLabels" . | nindent 4 }}
    app.nocobase/component: {{ include "nocobase.dbname" . }}
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
  type: ClusterIP
{{- end }}
