{{- if .Values.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{- .Values.persistence.volumeName }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{- .Values.persistence.size }}
  storageClassName: {{- .Values.persistence.storageClass }}
  {{- end }}