{{- if .Values.environmentSecrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "frigate.fullname" . }}
  labels:
    {{- include "frigate.labels" . | nindent 4 }}
data:
  {{- range $var, $value := .Values.environmentSecrets }}
    {{ $var }}: {{ $value }}
  {{- end }}
{{- end }}
---
{{- range .Values.additionalSecrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .name }}
  labels:
    {{- include "frigate.labels" $ | nindent 4 }}
type: Opaque
data:
  {{- toYaml .data | nindent 2 }}
{{- end }}